name: contbb
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.17.1 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  widgetbook: 2.0.5-beta
  flutter_svg: ^1.0.3
  auto_size_text: 3.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/contbb/assets/images/group.svg
    - packages/contbb/assets/images/bar.svg
    - packages/contbb/assets/images/closedarrow.png
    - packages/contbb/assets/images/unnoticed.svg
    - packages/contbb/assets/images/opennedarrow.png
    - packages/contbb/assets/images/correct.svg
    - packages/contbb/assets/images/wrong.svg
    - packages/contbb/assets/images/rectangle528.svg
    - packages/contbb/assets/images/background.svg
    - packages/contbb/assets/images/close.png
